// Generated by scripts/generate-intro-glyphs.py; source font: RobotoFlex-OFL.txt.
export const introGlyphs: Record<string, { outline: string; transform: string; brushTransform: string; strokes: string[] }> = {
  "S": {
    "outline": "M34 347Q34 179 147.0 79.5Q260 -20 449 -20Q637 -20 747.5 78.5Q858 177 858 338Q858 498 771.0 591.0Q684 684 460 765Q236 846 149.0 928.0Q62 1010 62 1159Q62 1308 157.0 1387.0Q252 1466 446 1466Q649 1466 735.5 1362.5Q822 1259 822 1133V1065H832V1135Q832 1263 742.5 1369.5Q653 1476 445 1476Q252 1476 151.5 1394.5Q51 1313 51 1159Q51 1006 141.0 921.5Q231 837 456 755Q681 673 764.5 583.5Q848 494 848 337Q848 182 741.0 86.0Q634 -10 451 -10Q264 -10 154.0 87.0Q44 184 44 359V427H34Z",
    "transform": "translate(424.4 1724.0) scale(1 -1)",
    "brushTransform": "translate(34 1476) scale(8.24 -14.96)",
    "strokes": [
      "M95 14 C72 -10 4 -5 4 25 C4 50 94 48 96 74 C102 106 30 112 2 85"
    ]
  },
  "E": {
    "outline": "M150 0H856V10H160V749H748V759H160V1446H846V1456H150Z",
    "transform": "translate(423.9 1724.0) scale(1 -1)",
    "brushTransform": "translate(150 1456) scale(7.06 -14.56)",
    "strokes": [
      "M4 0V100",
      "M4 2H100",
      "M4 49H88",
      "M4 98H100"
    ]
  },
  "M": {
    "outline": "M150 0H160V1418Q160 1420 160.0 1425.0Q160 1430 160 1438H161Q163 1431 164.5 1427.0Q166 1423 167 1421L689 0H696L1209 1426Q1211 1431 1212.0 1434.5Q1213 1438 1215 1443H1217Q1217 1436 1217.0 1432.5Q1217 1429 1217 1424V0H1227V1456H1209L703 46Q701 40 696.5 28.5Q692 17 692 13Q692 17 688.5 28.0Q685 39 682 46L165 1456H150Z",
    "transform": "translate(181.89999999999998 1724.0) scale(1 -1)",
    "brushTransform": "translate(150 1456) scale(10.77 -14.56)",
    "strokes": [
      "M2 100V0L50 100L98 0V100"
    ]
  },
  "I": {
    "outline": "M154 0H164V1456H154Z",
    "transform": "translate(711.4 1724.0) scale(1 -1)",
    "brushTransform": "translate(154 1456) scale(0.1 -14.56)",
    "strokes": [
      "M50 0V100"
    ]
  },
  "V": {
    "outline": "M0 1456 485 -9H495L980 1456H970L518 93Q512 76 505.5 55.0Q499 34 491 9H489Q481 34 474.0 56.0Q467 78 463 89L10 1456Z",
    "transform": "translate(380.4 1724.0) scale(1 -1)",
    "brushTransform": "translate(0 1456) scale(9.8 -14.65)",
    "strokes": [
      "M0 0L50 100L100 0"
    ]
  },
  "R": {
    "outline": "M150 0H160V669H496Q694 669 788.0 779.0Q882 889 882 1065Q882 1239 783.5 1347.5Q685 1456 496 1456H150ZM160 679V1446H496Q678 1446 775.0 1341.5Q872 1237 872 1065Q872 892 779.5 785.5Q687 679 496 679ZM934 0H946L591 681H579Z",
    "transform": "translate(377.4 1724.0) scale(1 -1)",
    "brushTransform": "translate(150 1456) scale(7.96 -14.56)",
    "strokes": [
      "M2 100V0H53C113 0 115 52 54 52H2",
      "M54 52L100 100"
    ]
  },
  "T": {
    "outline": "M10 1446H465V0H475V1446H930V1456H10Z",
    "transform": "translate(400.4 1724.0) scale(1 -1)",
    "brushTransform": "translate(10 1456) scale(9.2 -14.56)",
    "strokes": [
      "M0 2H100",
      "M50 2V100"
    ]
  }
}
