"""Generate the seven intro glyph outlines from the existing OFL font (fonttools)."""
import json
from pathlib import Path
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.boundsPen import BoundsPen

root = Path(__file__).resolve().parents[1]
font = instantiateVariableFont(TTFont(root / 'src/shared/assets/fonts/RobotoFlex-Weight-Latin.woff2'), {'wght': 100})
glyphs, cmap = font.getGlyphSet(), font.getBestCmap()
result = {}
# Centerline writing order, mapped into each actual glyph's bounds. The broad
# pen is only a mask; the visible outline remains the exact Roboto Flex glyph.
strokes = {
    'S': ['M95 14 C72 -10 4 -5 4 25 C4 50 94 48 96 74 C102 106 30 112 2 85'],
    'E': ['M4 0V100', 'M4 2H100', 'M4 49H88', 'M4 98H100'],
    'M': ['M2 100V0L50 100L98 0V100'],
    'I': ['M50 0V100'],
    'V': ['M0 0L50 100L100 0'],
    'R': ['M2 100V0H53C113 0 115 52 54 52H2', 'M54 52L100 100'],
    'T': ['M0 2H100', 'M50 2V100'],
}
for char, lines in strokes.items():
    name = cmap[ord(char)]
    pen, bounds = SVGPathPen(glyphs), BoundsPen(glyphs)
    glyphs[name].draw(pen)
    glyphs[name].draw(bounds)
    x0, y0, x1, y1 = bounds.bounds
    width = font['hmtx'][name][0]
    slot = font['head'].unitsPerEm * .85
    baseline = (2048 - (1900 + 500)) / 2 + 1900
    result[char] = {
        'outline': pen.getCommands(),
        'transform': f'translate({(slot - width) / 2} {baseline}) scale(1 -1)',
        'brushTransform': f'translate({x0} {y1}) scale({(x1-x0)/100} {-(y1-y0)/100})',
        'strokes': lines,
    }
destination = root / 'src/widgets/hero-section/model/introGlyphs.ts'
destination.write_text('// Generated by scripts/generate-intro-glyphs.py; source font: RobotoFlex-OFL.txt.\n'
    + 'export const introGlyphs: Record<string, { outline: string; transform: string; brushTransform: string; strokes: string[] }> = '
    + json.dumps(result, indent=2) + '\n', encoding='utf-8')
